Completed the javascript-if exercise.
yahnbaron/c1022-code-solutions pull request #33
Opened 2022-10-19 21:14 UTC by yahnbaron

![image](https://user-images.githubusercontent.com/113651780/196805665-e73e62d2-3325-4c1e-a0d0-ec08ee475574.png)

2022-10-19 21:31 UTC, codingcodymiller requested changes

2022-10-19 21:31 UTC, codingcodymiller commented on javascript-if/main.js
> +  if (name === 'yakko' || name === 'wakko' || name === 'dot') {
If it's `dot`, you are supposed to return `"I'm cute~"`

2022-10-19 21:45 UTC, yahnbaron commented
![image](https://user-images.githubusercontent.com/113651780/196810757-9ce69f8f-0b1e-40e3-8fa6-7f5c7000e57b.png)

2022-10-20 18:47 UTC, codingcodymiller approved these changes

2022-10-20 18:49 UTC, merged